// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	KeyPairId         *string `json:",omitempty"`
	KeyFingerprint    *string `json:",omitempty"`
	KeyName           *string `json:",omitempty"`
	KeyType           *string `json:",omitempty"`
	PublicKeyMaterial *string `json:",omitempty"`
	Tags              []Tag   `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
